# Generated by Django 4.2.30 on 2026-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_image_url', models.URLField(max_length=500)),
                ('original_image_filename', models.CharField(max_length=255)),
                ('stego_image_url', models.URLField(max_length=500)),
                ('stego_image_filename', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='encode',
            constraint=models.UniqueConstraint(fields=('email', 'title'), name='unique_email_title'),
        ),
    ]
